name: Test Project
on:
  pull_request: 
    branches: 
      -main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:python:3.10
    steps:
      -uses: actions/checkout@v3
        with:
          python-version:3.10
